version: "3.6"

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: 3.9

x-default-volumes: &default_volumes
  volumes:
    - ./:/app
    - ./dev.db:/tmp/dev.db

x-postgres-volumes: &postgres_volumes
  volumes:
    # named volumes
    - 'postgres:/var/lib/postgresql/data'


services:
  flask-dev:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    image: "url_shortener-development"
    ports:
      - "12000:5000"
    <<: *default_volumes

  flask-prod:
    build:
      context: .
      target: production
      args:
        <<: *build_args
    image: "url_shortener-production"
    ports:
      - "12000:5000"
    depends_on:
      - "postgres"
    env_file:
      - '.env'
    <<: *default_volumes

  manage:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    entrypoint: flask
    depends_on:
      - "postgres"
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
    image: "url_shortener-manage"
    stdin_open: true
    tty: true
    <<: *default_volumes

  postgres:
    env_file:
      - '.env'
    image: 'postgres:10.3-alpine'
    ports:
      - '5410:5432'
    <<: *postgres_volumes


volumes:
  postgres: { }
